### ISSUE TITLE
[MMHook Standalone. you dont have a repo for it] You forgot the files

### ISSUE THREAD

**Issue by VaelophisNyx** [xoxfaby/BetterAPI#6]
MMHook 1.0.3 contains 
![ss (2021-04-15 at 03 12 13)](https://user-images.githubusercontent.com/1534478/114938945-facd2580-9dfc-11eb-8e14-905991f6f761.png)
and nothing else

**Comment by xoxfaby** [comment]
This is intentional, the recommend mod to use now is HookGenPatcher which is now a dependancy of MMHOOK Standalone

**Comment by VaelophisNyx** [comment]
why not mark it as depreciated then?

**Comment by xoxfaby** [comment]
Because that breaks any mod using it for no good reason
